/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class HuffmanZipTest {
    @Test public void initializationTest() {
        HuffmanZip huffmanZip = new HuffmanZip();
    }
}
